# Generated by Django 2.2.4 on 2019-09-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasoauthtoken',
            name='canvas_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='canvasoauthtoken',
            name='access_token',
            field=models.TextField(unique=True),
        ),
    ]
