# Generated by Django 2.2.4 on 2019-08-08 13:14

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HiringOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inserted_at', models.DateTimeField(auto_now=True)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Hiring_Organizations',
                'db_table': 'hiring_organizations',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('host', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Providers',
                'db_table': 'providers',
            },
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('employment_type', models.CharField(max_length=255, null=True)),
                ('date_posted', models.DateField(null=True)),
                ('valid_to', models.DateField(null=True)),
                ('url', models.TextField()),
                ('months', models.PositiveIntegerField()),
                ('industry', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('education_requirements', models.TextField(null=True)),
                ('qualifications', models.TextField(null=True)),
                ('responsibilities', models.TextField(null=True)),
                ('instructions', models.TextField(null=True)),
                ('hiring_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_jobs', to='jobs.HiringOrganization')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provder_jobs', to='jobs.Provider')),
            ],
            options={
                'verbose_name_plural': 'JobListings',
                'db_table': 'job_listings',
            },
        ),
    ]
