# Generated by Django 2.2.2 on 2019-06-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190611_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providers',
            name='url',
        ),
    ]
