# Generated by Django 2.2.4 on 2019-08-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190808_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
