# Generated by Django 2.2.4 on 2019-08-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190809_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='months',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
