# Generated by Django 2.2.2 on 2019-06-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_providers_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
