# Generated by Django 2.2.4 on 2019-08-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20190809_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='industry',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
