# Generated by Django 2.2.4 on 2019-08-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20190809_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblisting',
            old_name='tags',
            new_name='technologies',
        ),
    ]
