# Generated by Django 2.2.4 on 2019-08-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_serversyncjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='location',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
